# Generated by Django 4.2.30 on 2026-06-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(choices=[('CAD', 'Canadian Dollar')], default='CAD', max_length=3)),
                ('description', models.TextField()),
                ('best_for', models.JSONField(default=list)),
                ('salary_income', models.BooleanField(default=False)),
                ('student_income', models.BooleanField(default=False)),
                ('medical_expenses', models.BooleanField(default=False)),
                ('donations', models.BooleanField(default=False)),
                ('employment_expenses', models.BooleanField(default=False)),
                ('family_deductions', models.BooleanField(default=False)),
                ('investment_income', models.BooleanField(default=False)),
                ('capital_gains', models.BooleanField(default=False)),
                ('foreign_income', models.BooleanField(default=False)),
                ('rental_income', models.BooleanField(default=False)),
                ('freelance_income', models.BooleanField(default=False)),
                ('gig_work_income', models.BooleanField(default=False)),
                ('business_expenses', models.BooleanField(default=False)),
                ('home_office_expenses', models.BooleanField(default=False)),
                ('vehicle_expenses', models.BooleanField(default=False)),
                ('expert_help', models.BooleanField(default=False)),
                ('full_service', models.BooleanField(default=False)),
                ('corporate_filing', models.BooleanField(default=False)),
                ('nil_corporate_return', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
    ]
